name: 24f1002474@ds.study.iitm.ac.in
on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 02:30 UTC (fixed the syntax)
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Ensure GitHub Actions can push changes

jobs:
  commit:
    name: 24f1002474@ds.study.iitm.ac.in  # Add this line to include email in job name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "24f1002474@ds.study.iitm.ac.in"
          
      - name: Make a Change
        run: |
          echo "Last run: $(date)" > last_run.txt
          
      - name: Commit and Push Changes
        run: |
          git add last_run.txt
          git commit -m "Automated daily commit at $(date)" || echo "No changes to commit"
          git push
