name: 24f1002474@ds.study.iitm.ac.in  # Workflow name
on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    name: 24f1002474@ds.study.iitm.ac.in  # Job name must match exactly
    runs-on: ubuntu-latest
    steps:
      - name: 24f1002474@ds.study.iitm.ac.in  # Step name should also match
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "24f1002474@ds.study.iitm.ac.in"

      - name: Make a Change
        run: |
          echo "Last run: $(date)" > last_run.txt

      - name: Commit and Push Changes
        run: |
          git add last_run.txt
          git commit -m "Automated daily commit by 24f1002474@ds.study.iitm.ac.in at $(date)" || echo "No changes to commit"
          git push
